#! /bin/bash

sqlite3 -bail << EOF

.import --csv "$1" tmp
.mode json

WITH cte AS (
    SELECT
        CAST(mpid AS INT) AS mpid,
        CAST(date AS INT) AS date,
        '0000000' AS requestId
    FROM tmp
    ORDER BY mpid, date
)   

SELECT
    mpid || '-' || date AS "Id",
    json_object(
        'masterPortfolioId', mpid,
        'portfolioDate', date
    ) AS "MessageBody"
FROM cte
;

EOF
