#! /bin/sh

REALPATH=$(realpath "$1")

sqlite3 -bail << EOF

.import --csv "$REALPATH" csv
.mode json

WITH cte AS (
    SELECT DISTINCT
        CAST(mpid AS INT) AS mpid,
        CAST(date AS INT) AS date
    FROM csv
    ORDER BY mpid, date
)   

SELECT
    mpid || '-' || date AS "Id",
    json_object(
        'masterPortfolioId', mpid,
        'portfolioDate', date,
        'requestId', '0000'
    ) AS "MessageBody"
FROM cte
;

EOF
