#! /bin/sh

sqlite3 -bail << EOF

.import --csv "$1" tmp
.mode json

WITH cte AS (
    SELECT DISTINCT
        CAST(mpid AS INT) AS mpid,
        CAST(date AS INT) AS date
    FROM tmp
    ORDER BY mpid, date
)   

SELECT
    mpid || '-' || date AS "Id",
    json_object(
        'masterPortfolioId', mpid,
        'portfolioDate', date,
        'requestId', HEX(RANDOMBLOB(CURRENT_TIME))
    ) AS "MessageBody"
FROM cte
;

EOF
