#!/bin/sh

mv "$HOME/.aws/credentials" "$HOME/.aws/credentials.$(date +%FT%T)"

echo """
[default]
$(pbpaste | egrep 'aws_access_key_id|aws_secret_access_key|aws_session_token')

[duckdb]
$(pbpaste | egrep 'aws_access_key_id|aws_secret_access_key|aws_session_token')

[prod]
""" tr -d '\r' > "$HOME/.aws/credentials"

aws sts get-caller-identity --no-cli-pager --profile default

