#!/bin/sh
set -o errexit
set -o pipefail


clusters=(
	personal-fm
	ps-ca
	ps-cp
	ps-etl
	ps-gv
	ps-mv
	ps-pcs
	ps-pcs-od
	ps-sust
)

for cluster in "${clusters[@]}"
do
	aws ecs list-services --cluster="${cluster}" --output=json \
		| jq --raw-output '.serviceArns[]' \
		| sort \
		| xargs -L10 aws ecs describe-services --no-cli-pager --output=json \
			--query "services[?desiredCount>=\`1\` || runningCount>=\`1\`].{desired:desiredCount, running:runningCount, service:serviceName, cluster:\`${cluster}\`}" \
			--cluster "${cluster}" --services \
		| jq --compact-output '.[]' \
		| duckdb -c '.mode box' -c "SELECT running, desired, service, cluster FROM READ_NDJSON('/dev/stdin');" \
	;
done
