#!/bin/sh
set -o errexit
set -o pipefail
set -o noclobber

sink=$(mktemp -u)
mkfifo "$sink"
trap 'rm -f "$sink"' EXIT


repos=(
	DATACALC/calculation-sdk
	DATAAPI/kafka-consumers
)

for repo in "${repos[@]}"
do
	git -c versionsort.suffix=- ls-remote --exit-code --refs --sort=version:refname --tags "ssh://git@stash.example.com/${repo}.git" '[0-9].[0-9][0-9].[0-9]*' \
		| tail -n 1 \
		| xargs -I{} echo {} "$repo" > "$sink" &

done
wait

cat "$sink" | sort -k3 | sed -e 's: :\t:g'

