#! /usr/bin/env python3
import sys

def hell(s, arr):
    if not arr:
        print(s)
    else:
        hell(s + '_' + arr[0], arr[1:])
        hell(s + '__' + arr[0], arr[1:])

arr = list(filter(None, sys.argv[1].split('_')))
hell(s=arr[0], arr=arr[1:])
