#! /usr/bin/env python3
import sys

def hell(s, tokens):
    if tokens:
        hell(s + '_' + tokens[0], tokens[1:])
        hell(s + '__' + tokens[0], tokens[1:])
    print(s)

tokens = list(filter(None, sys.argv[1].split('_')))
hell(s=tokens[0], tokens=tokens[1:])
