#! /bin/sh

REALPATH=$(realpath "$1")

sqlite3 -bail << EOL

.import --csv "$REALPATH" csv
.excel

WITH cte AS (
    SELECT 
        " User" AS user,
        SUBSTR("Incident", 10) AS incident
    FROM csv
    WHERE " User" IN ('hamza.boutou', 'SYSTEM')
        AND " Event" = 'RESOLVED'
)

SELECT
    user,
    COUNT(incident),
    incident
FROM cte
GROUP BY incident, user
ORDER BY user, COUNT(incident) DESC
;

EOL
