#! /bin/sh

REALPATH=$(realpath "$1")

sqlite3 -bail << EOL
.import --csv "$REALPATH" csv
.excel

WITH cte AS (
    SELECT 
        " User" AS "user",
        SUBSTR("Incident", 10) AS "incident",
        " Date Time (UTC)" AS datetime_utc,
        " Event" AS event
    FROM csv
)
SELECT
    user,
    COUNT(incident) AS "cnt",
    GROUP_CONCAT(CAST(strftime('%d', datetime_utc) AS INT)) AS days,
    incident
FROM cte
WHERE TRUE
    -- AND user IN ('hamza.boutou','SYSTEM')
    -- AND event = 'RESOLVED' -- 'ACKED'
GROUP BY incident, user
ORDER BY user, COUNT(incident) DESC
;

EOL
