#! /usr/bin/env lua

while true do
    io.write("continue (yes/no) ? ")
    choice = io.read()

    if choice == "yes" then
        os.exit(0)
    elseif choice == "no" then
        os.exit(1)
    else
        print("type yes or no")
    end
end
